### PR TITLE
Revert "Add doChores before muling if lowGold is set"

### PR DESCRIPTION
**Pull request by jaenster**
Reverts blizzhackers/kolbot#45

### CODE REVIEW

**Comment by jaenster** [comment]
i really dislike to revert, as it messes with the history.


@jmichelsen once we fix'd the issue we need to merge it again (freshly as a new commit)

**Comment by macohan** [comment]
ill look at this some tomorrow and see what i can come up with
 something like a check for stash/inventory space threshold being met before and after townchores if lowgold is set 
that way you can sell off in the same game instead of going to make a unneeded normal game where you just end up selling items and not actually dropping anything

**Comment by jmichelsen** [comment]
My original change meant mules happened maybe 1 or 2 drops early but there wasn't any wasted game. I was still testing moving that elsewhere but wasn't satisfied with the results, that's why I hadn't pushed any changes to the original pr yet. I can continue work on this this weekend.

**Comment by mf022** [comment]
> i really dislike to revert, as it messes with the history.
> 

idk why this had to be pushed before other fix arrived.

maybe some guys had to pay more attention to their own modded kolbot which it isn't very functional, and they should not find a reason to disagree anything which is coming from other part.

**Pull request merged**
