### PR TITLE
Issue 390: Weapons not switching back to primary with Config.TeleSwitch enabled

### LINKED ISSUE #390: Weapons not switching back to primary with `Config.TeleSwitch` enabled
**Before filling this out**
1. Check [The documentation repo](https://github.com/blizzhackers/documentation/blob/master/kolbot/FAQ.md/#faq) to see if your answer is there.
2. Check that your download is up to date.
3. Search though existing open and closed issues to ensure this is not a duplicate.
4. Is it really a bug? If you are unsure then join the discord server and ask about it first.

**Describe the bug**
When `Config.TeleSwitch` is enabled, weapons are not be switch back to the primary set before attacking.

**Can you reproduce it?**
1. Set `Config.TeleSwitch = true`
2. Set `Config.PrimarySlot = 0` where Slot I has your damage weapons and Slot II has your teleport weapons
3. Run a bot which teleports more than five nodes without attacking (to engage teleport switching) and then attacks something
4. Note that then the bot begins to attack it is still using Slot II (teleport weapons) and not Slot I (primary weapons)

**Expected behavior**
1. When the bot begins to attack I expect it to use the primary weapons slot as configured

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Additional context**

### PR DESCRIPTION
**Pull request by samlitowitz**
Resolves #390

### CODE REVIEW

**Comment by samlitowitz** [comment]
@theBGuy for visibility.

**Comment by theBGuy** [comment]
Nothing new is being added to mainline. Its just awaiting the restructure branch to be finished and merged

**Comment by samlitowitz** [comment]
@theBGuy is there an ETA on the completion of the restructure? Is there something you would like help with on the restructure?

**Comment by theBGuy** [comment]
I don't have an eta at this time. I originally thought this would take me about a year but for the past couple months I've had little to no time to work on this. I know there are some bugs that have been reported in the blizzhackers discord. Figuring out those would be helpful.

**Pull request closed without merging**
