### PR TITLE
Numpad '+' also print merc stats and remove magic numbers using sdk.js

### PR DESCRIPTION
**Pull request by ChefKeeper**
Also added few more stats : 

- max res for each res
- Calculate hell res taking into account the max res value (usefull when muling items for your char in normal)

### CODE REVIEW

**Comment by ChefKeeper** [comment]
Forgot to add `require(../module/sdk)`
But I think that there is a bug with the require part because adding `require(../libs/module/sdk)` it throws saying the file is not found

**Comment by jaenster** [comment]
@ChefKeeper i gonna investigate =)

**Comment by jaenster** [comment]
https://github.com/ChefKeeper/kolbot/pull/1

Please update your master with this, it contains the fix for the issue you found, for which thanks by the way.

**Comment by ChefKeeper** [comment]
Thanks @jaenster merged your fix and now works 👍

**Pull request merged**
