### PR TITLE
Gem Hunter

### PR DESCRIPTION
**Pull request by icommitdesnet**
Gem Hunting script.
- Always try to keep the best gem from Config.GemHunter.GemList in inventory, if Config.ScanShrines contains a Gem Shrine
- Bot to scan areas for Gem Shrine. gets only the first gem shrine each area.

### CODE REVIEW

**Comment by theBGuy** [comment]
Looks fine for the most part, can you go over it using eslint. You have some formatting issues, e.g using == instead of strict equality ===, spacing, brackets, ect. Also this line isn't doing anything
```js
Config.ScanShrines.filter((p) => p != sdk.shrines.Gem);
```
as filter doesn't modify the original array.

In Town.js this: 
```js
canStashGem: function (item) {

		if (!(Scripts.GemHunter || Config.ScanShrines.includes(sdk.shrines.Gem)))
			return true;

		let GemList = Config.GemHunter.GemList;

		let bestGeminStash;
		if (this.getGemsInStash().length > 0)
			bestGeminStash = this.getGemsInStash().first().classid;

		let bestGeminInv;
		if (this.getGemsInInv().length > 0)
			bestGeminInv = this.getGemsInInv().first().classid;

		return (GemList.indexOf(item.classid) < 0) ||
		       (GemList.indexOf(bestGeminStash) < GemList.indexOf(bestGeminInv)) ||  // better one in stash
			   (GemList.indexOf(bestGeminInv) < GemList.indexOf(item.classid)) ||       // better one in inv
		       (this.getGemsInInv().filter((p) => p.classid == item.classid).length > 1);  // another one in inv
	}
```
Would be better written
```js
	/**
	 * gem check for use with Gem Hunter Script
	 * @param {ItemUnit} item 
	 * @returns {boolean} if we should stash this gem
	 */
	canStashGem: function (item) {
		// we aren't using the gem hunter script or we aren't scanning for the gem shrines
		if (!Scripts.GemHunter || !Config.ScanShrines.includes(sdk.shrines.Gem)) return true;
		// not in our list
		if (Config.GemHunter.GemList.indexOf(item.classid) === -1) return true;

		let GemList = Config.GemHunter.GemList;
		let gemsInStash = Town.getGemsInStash();
		let bestGeminStash = gemsInStash.length > 0 ? gemsInStash.first().classid : -1;
		let gemsInInvo = Town.getGemsInInv();
		let bestGeminInv = gemsInInvo.length > 0 ? gemsInInvo.first().classid : -1;

		return (
			(GemList.indexOf(bestGeminStash) < GemList.indexOf(bestGeminInv)) // better one in stash
			|| (GemList.indexOf(bestGeminInv) < GemList.indexOf(item.classid)) // better one in inv
			|| (gemsInInvo.filter((p) => p.classid === item.classid).length > 1));  // another one in inv
	},
```

You also have some oops commits that should be cleaned up, start this over from a clean branch to fix that

**Comment by icommitdesnet** [comment]
sorry for the mess. eslint revealed a lot.

**Comment by theBGuy** [comment]
Looks much better, you can actually remove this section though
```js
// let GemHunter Pick the shrines and not the Pather
	let initalScanShrines = Config.ScanShrines;
	Config.ScanShrines = Config.ScanShrines.filter((p) => p !== sdk.shrines.Gem);
```

I added awhile back that when using `Misc.getShrinesInArea` it automatically excludes the type passed in from NodeAction. Also just to note that wouldn't be the way to copy the values of an array. You would need to use slice() otherwise
```js
const temp = [1, 2, 3, 4];
const copied = temp;
temp.pop(); // remove last element from temp
console.log(copied); // would also have the last element removed so would log 1, 2, 3
```

**Comment by icommitdesnet** [comment]
removed the messing with user config Config.ScanShrines. was a bad solution anyway.
Base and upgraded version of gem will be autopicked and kept for cubing now.

**Pull request merged**
