### PR TITLE
add some missing location handling in entry scripts

### PR DESCRIPTION
**Pull request by stffdtiger**
* location 40 = TCP/IP Game menu
when hosting a TCP/IP game, after the game ends you land on location 40, but this wasn't handled before. just press Esc to go back to location 39.
* location 39 = Other Multiplayer menu
just press Esc to go back to Main Menu.

### CODE REVIEW

**Comment by jaenster** [comment]
Nice, maybe an idea to add `// esc`` after the send key, so we know what `0x1B` stands for, for the rest, nice

**Comment by noah-** [comment]
so I added another location to d2bs to handle this, I sort of implemented the fix here:
https://gist.github.com/noah-/1746508a15d7044015782a71145bfa75

can you port this to the other starters?

**Comment by stffdtiger** [comment]
I started working on this, but I ran into an issue that was already present. location 41, which is the "Enter Host IP" dialog box when using D2BotFollow on TCP/IP, was not handled which means that the bot just restarts over and over again. I tried using `login(me.profile)` but I got an error about not being able to get the IP address from d2bs.ini. I'm guessing this is something D2Bot# has to manage.

**Comment by noah-** [comment]
the ip address is the same thing as "account" for tcpip, for example, you can put "localhost" for account and it should work

**Comment by stffdtiger** [comment]
I added the location handling to all the applicable entry scripts. I also did some cleanup, so check it out and make sure what I did was acceptable.

**Pull request merged**
