### PR TITLE
Update D2BotMap

### PR DESCRIPTION
**Pull request by theBGuy**

### CODE REVIEW

**Comment by theBGuy** [comment]
UpdatedBotMapOverlay

-Added exit names and shrine names

**Comment by fabio1999ita** [comment]
can you also move a little bit to bottom for read your chat

**Comment by theBGuy** [comment]
updatedOverlay

-Got rid of excessive empty space



> can you also move a little bit to bottom for read your chat

I made it so when opening the chat box the text there disappears

**Comment by fabio1999ita** [comment]
> I made it so when opening the chat box the text there disappears
so good

**Comment by jaenster** [comment]
This branch is a mess, i gonna close it

**Pull request closed without merging**
